Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,118 +34,118 @@ version: 2.1
 #           fi
 
 jobs:
-  build-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: Build front-end
-          command: |
-            cd frontend
-            npm install
-            # npm audit fix
-            npm run build
-            # exit 1
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-build
+  # build-frontend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [frontend-build]
+  #     - run:
+  #         name: Build front-end
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           # npm audit fix
+  #           npm run build
+  #           # exit 1
+  #     - save_cache:
+  #         paths: [frontend/node_modules]
+  #         key: frontend-build
 
-  build-backend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Back-end build
-          command: |
-            cd backend
-            npm install
-            # npm audit fix
-            npm run build
-            # exit 1
-      - save_cache:
-          paths: [backend/node_modules]
-          key: backend-build
+  # build-backend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-build]
+  #     - run:
+  #         name: Back-end build
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           # npm audit fix
+  #           npm run build
+  #           # exit 1
+  #     - save_cache:
+  #         paths: [backend/node_modules]
+  #         key: backend-build
 
-  test-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-test]
-      - run:
-          name: Front-end test
-          command: |
-            cd backend
-            npm install
-            npm run test
-            # exit 1
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-test
+  # test-frontend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [frontend-test]
+  #     - run:
+  #         name: Front-end test
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           npm run test
+  #           # exit 1
+  #     - save_cache:
+  #         paths: [frontend/node_modules]
+  #         key: frontend-test
 
-  test-backend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-test]
-      - run:
-          name: Back-end test
-          command: |
-            cd backend
-            npm install
-            npm run test
-            # exit 1
-      - save_cache:
-          paths: [backend/node_modules]
-          key: test-build
+  # test-backend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-test]
+  #     - run:
+  #         name: Back-end test
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           npm run test
+  #           # exit 1
+  #     - save_cache:
+  #         paths: [backend/node_modules]
+  #         key: test-build
 
-  scan-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-scan]
-      - run:
-          name: Front-end scan
-          command: |
-            cd frontend
-            npm install
-            npm audit fix --audit-level=critical --force
-            npm audit --audit-level=critical
-            # exit 1
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-scan
+  # scan-frontend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [frontend-scan]
+  #     - run:
+  #         name: Front-end scan
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           npm audit fix --audit-level=critical --force
+  #           npm audit --audit-level=critical
+  #           # exit 1
+  #     - save_cache:
+  #         paths: [frontend/node_modules]
+  #         key: frontend-scan
 
-  scan-backend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-scan]
-      - run:
-          name: Back-end scan
-          command: |
-            cd backend
-            npm install
-            npm audit fix --audit-level=critical --force
-            npm audit fix --force
-            npm audit --audit-level=critical
-            # exit 1
-      - save_cache:
-          paths: [backend/node_modules]
-          key: backend-scan
+  # scan-backend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-scan]
+  #     - run:
+  #         name: Back-end scan
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           npm audit fix --audit-level=critical --force
+  #           npm audit fix --force
+  #           npm audit --audit-level=critical
+  #           # exit 1
+  #     - save_cache:
+  #         paths: [backend/node_modules]
+  #         key: backend-scan
 
   deploy-infrastructure:
     docker:
@@ -207,37 +207,38 @@ jobs:
           name: Configure server
           command: |
             cd .circleci/ansible
+            cat  ~/project/.circleci/ansible/inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
             # exit 1
       # - destroy-environment
       # Here's where you will add some code to rollback on failure
 
-  run-migrations:
-    docker:
-      - image: cimg/node:15.0.1
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Run migrations
-          command: |
-            cd backend
-            npm install   
-            npm run migrations > migrations_dump.txt            
-            echo "Contents  of the migration file is -------"
-            cat migrations_dump.txt
-      - run:
-          name: Send migration status to kvdb.io OR memstash.io
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            echo "Migrations completed successfully"
-            then                 
-              curl --insecure https://kvdb.io/NZrFCGtxSFcjgKnJBPWGHY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-            fi
-          # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      # - destroy-environment:
-      # Here's where you will add some code to rollback on failure
+  # run-migrations:
+  #   docker:
+  #     - image: cimg/node:15.0.1
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-build]
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           npm install   
+  #           npm run migrations > migrations_dump.txt            
+  #           echo "Contents  of the migration file is -------"
+  #           cat migrations_dump.txt
+  #     - run:
+  #         name: Send migration status to kvdb.io OR memstash.io
+  #         command: |
+  #           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+  #           echo "Migrations completed successfully"
+  #           then                 
+  #             curl --insecure https://kvdb.io/NZrFCGtxSFcjgKnJBPWGHY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+  #           fi
+  #         # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+  #     # - destroy-environment:
+  #     # Here's where you will add some code to rollback on failure
 
   # deploy-frontend:
   #   docker:
@@ -381,16 +382,16 @@ cleanup:
 workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
+      # - build-frontend
+      # - build-backend
+      # - test-frontend:
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           # filters:
@@ -398,8 +399,8 @@ workflows:
           # only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
