Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -231,6 +231,7 @@ jobs:
           name: Send migration status to kvdb.io OR memstash.io
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            echo "Migrations completed successfully"
             then                 
               curl --insecure https://kvdb.io/NZrFCGtxSFcjgKnJBPWGHY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
@@ -238,85 +239,85 @@ jobs:
       # - destroy-environment:
       # Here's where you will add some code to rollback on failure
 
-  deploy-frontend:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      # - run: yum install -y tar gzip
-      # - run: install nodejs npm
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update ansible
-            apk add --update gzip
-            apk add --update tar
-            apk add --update nodejs npm
-            pip install awscli
-            # exit 1
-      - run:
-          name: Get backend url
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --filters "Name=tag:project,Values=udapeople-backend" \
-              --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - restore_cache:
-          keys: [frontend-deploy]
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # - destroy-environment
-      #     # id: ${CIRCLE_WORKFLOW_ID:0:7}
-      # - revert-migrations:
-      #     id: ${CIRCLE_WORKFLOW_ID:0:7}
-      # Here's where you will add some code to rollback on failure
+  # deploy-frontend:
+  #   docker:
+  #     - image: python:3.7-alpine3.11
+  #   steps:
+  #     - checkout
+  #     # - run: yum install -y tar gzip
+  #     # - run: install nodejs npm
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           apk add --update ansible
+  #           apk add --update gzip
+  #           apk add --update tar
+  #           apk add --update nodejs npm
+  #           pip install awscli
+  #           # exit 1
+  #     - run:
+  #         name: Get backend url
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --filters "Name=tag:project,Values=udapeople-backend" \
+  #             --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "API_URL = ${API_URL}"
+  #           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+  #           cat frontend/.env
+  #     - restore_cache:
+  #         keys: [frontend-deploy]
+  #     - run:
+  #         name: Deploy frontend objects
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           npm run build
+  #           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+  #           aws s3 cp dist s3://udapeople-udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+  #     # - destroy-environment
+  #     #     # id: ${CIRCLE_WORKFLOW_ID:0:7}
+  #     # - revert-migrations:
+  #     #     id: ${CIRCLE_WORKFLOW_ID:0:7}
+  #     # Here's where you will add some code to rollback on failure
 
-  deploy-backend:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-deploy]
-      - add_ssh_keys:
-          fingerprints:
-            - "8f:ec:6d:80:9f:18:30:41:e1:04:a9:3b:02:3e:7a:b7"
-      - attach_workspace:
-          at: .circleci/ansible
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update ansible
-            apk add --update gzip
-            apk add --update nodejs npm
-            apk add tar
-            pip install awscli
-            # exit 1
-      - run:
-          name: Deploy backend
-          command: |
-            cd backend
-            npm i
-            npm run build
-            cd ..
-            # Zip the directory
-            tar -C backend -czvf artifact.tar.gz .
-            cd .circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
-            # cat inventory.txt
-            cat ~/project/.circleci/ansible/inventory.txt 
-            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt deploy-backend.yml
-            # ansible-playbook -i inventory.txt deploy-backend.yml
+  # deploy-backend:
+  #   docker:
+  #     - image: python:3.7-alpine3.11
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-deploy]
+  #     - add_ssh_keys:
+  #         fingerprints:
+  #           - "8f:ec:6d:80:9f:18:30:41:e1:04:a9:3b:02:3e:7a:b7"
+  #     - attach_workspace:
+  #         at: .circleci/ansible
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           apk add --update ansible
+  #           apk add --update gzip
+  #           apk add --update nodejs npm
+  #           apk add tar
+  #           pip install awscli
+  #           # exit 1
+  #     - run:
+  #         name: Deploy backend
+  #         command: |
+  #           cd backend
+  #           npm i
+  #           npm run build
+  #           cd ..
+  #           # Zip the directory
+  #           tar -C backend -czvf artifact.tar.gz .
+  #           cd .circleci/ansible
+  #           echo "Contents  of the inventory.txt file is -------"
+  #           # cat inventory.txt
+  #           cat ~/project/.circleci/ansible/inventory.txt 
+  #           ansible-playbook -i ~/project/.circleci/ansible/inventory.txt deploy-backend.yml
+  #           # ansible-playbook -i inventory.txt deploy-backend.yml
       # Here's where you will add some code to rollback on failure
       # - destroy-environment
 
@@ -399,10 +400,10 @@ workflows:
           requires: [deploy-infrastructure]
       - run-migrations:
           requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
       # - smoke-test:
       #     requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
