AddTest

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      # Add parameter here
     steps:
       - run:
           name: Destroy environments
@@ -16,7 +16,7 @@ commands:
   # revert-migrations:
   #   description: Revert the last migration if successfully run in the current workflow.
   #   parameters:
-  #     # Add parameter here     
+  #     # Add parameter here
   #   steps:
   #     - run:
   #         name: Revert migrations
@@ -24,14 +24,14 @@ commands:
   #         command: |
   #           # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
   #           SUCCESS = 1
-  #           if(( $SUCCESS==1 )); 
+  #           if(( $SUCCESS==1 ));
   #           then
   #           #  cd ~/project/backend
   #           #  npm install
   #           #  Add revert code here. You can find this in the Getting Started section.
   #             exit 1
   #           fi
-            
+
 jobs:
   build-frontend:
     docker:
@@ -69,22 +69,42 @@ jobs:
           paths: [backend/node_modules]
           key: backend-build
 
-  # test-frontend:
-  #   docker:
-  #     # Docker image here
-  #   steps:
-  #     # Checkout code from git
-  #     # Restore from cache
-  #     # Your job code here
-                
-  # test-backend:
-  #   docker:
-  #     # Docker image here
-  #   steps:
-  #     # Checkout code from git
-  #     # Restore from cache
-  #     # Your job code here
-            
+  test-frontend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [frontend-test]
+      - run:
+          name: Front-end test
+          command: |
+            cd backend
+            npm install
+            npm run test
+            exit 1
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-test
+
+  test-backend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-test]
+      - run:
+          name: Back-end test
+          command: |
+            cd backend
+            npm install
+            npm run test
+            exit 1
+      - save_cache:
+          paths: [backend/node_modules]
+          key: test-build
+
   # scan-frontend:
   #   docker:
   #     # Docker image here
@@ -113,7 +133,7 @@ jobs:
   #             --template-file .circleci/files/backend.yml \
   #             #--tags project=your-tag \
   #             # --stack-name "your back-end stack name with workflow id" \
-  #             # --parameter-overrides ID="your workflow id"  
+  #             # --parameter-overrides ID="your workflow id"
   #             exit 1
   #     - run:
   #         name: Ensure front-end infrastructure exist
@@ -122,7 +142,7 @@ jobs:
   #             --template-file .circleci/files/frontend.yml \
   #             #--tags project=your-tag \
   #             # --stack-name "your front-end stack name with workflow id" \
-  #             # --parameter-overrides ID="your workflow id"  
+  #             # --parameter-overrides ID="your workflow id"
   #             exit 1
   #     - run:
   #         name: Add back-end ip to ansible inventory
@@ -133,7 +153,7 @@ jobs:
   #         root: ~/
   #         paths:
   #           - project/.circleci/ansible/inventory.txt
-  #     # Here's where you will add some code to rollback on failure      
+  #     # Here's where you will add some code to rollback on failure
 
   # configure-infrastructure:
   #   docker:
@@ -152,7 +172,7 @@ jobs:
   #         command: |
   #           # Your code here
   #           exit 1
-  #     # Here's where you will add some code to rollback on failure      
+  #     # Here's where you will add some code to rollback on failure
 
   # run-migrations:
   #   docker:
@@ -169,7 +189,7 @@ jobs:
   #         command: |
   #           # Your code here
   #           exit 1
-  #    # Here's where you will add some code to rollback on failure      
+  #    # Here's where you will add some code to rollback on failure
 
   # deploy-frontend:
   #   docker:
@@ -190,8 +210,8 @@ jobs:
   #         name: Deploy frontend objects
   #         command: |
   #           # your code here
-  #     # Here's where you will add some code to rollback on failure      
-                    
+  #     # Here's where you will add some code to rollback on failure
+
   # deploy-backend:
   #   docker:
   #     # Docker image here that supports Ansible
@@ -207,11 +227,11 @@ jobs:
   #         name: Deploy backend
   #         command: |
   #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+  #     # Here's where you will add some code to rollback on failure
 
   # smoke-test:
   #   docker:
-  #     # Lightweight Docker image 
+  #     # Lightweight Docker image
   #   steps:
   #     # Checkout code from git
   #     - run:
@@ -230,7 +250,7 @@ jobs:
   #         name: Frontend smoke test.
   #         command: |
   #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+  #     # Here's where you will add some code to rollback on failure
 
   # cloudfront-update:
   #   docker:
@@ -245,37 +265,36 @@ jobs:
   #         name: Update cloudfront distribution
   #         command: |
   #           # your code here
-  #     # Here's where you will add some code to rollback on failure  
+  #     # Here's where you will add some code to rollback on failure
 
 cleanup:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
+  docker:
+    # Docker image here
+  steps:
+    # Checkout code from git
+    - run:
+        name: Get old stack workflow id
+        command: |
+          # your code here
+          export OldWorkflowID="the id here"
+          export STACKS=[] #put the list of stacks here
+    - run:
+        name: Remove old stacks and files
+        command: |
+          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+          then
             # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              # your code here
-            fi
-            
+          fi
 
 workflows:
   default:
     jobs:
       - build-frontend
       - build-backend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - test-backend:
-      #     requires: [build-backend]
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
       # - scan-backend:
       #     requires: [build-backend]
       # - scan-frontend:
